import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

export async function GET() {
    try {
        // Clear existing properties
        await prisma.property.deleteMany({})

        const properties = [
            {
                title: 'Modern Apartment in City Center',
                description: 'A beautiful 2-bedroom apartment with city views and modern amenities. Located in the heart of downtown with easy access to public transportation.',
                price: 250000,
                location: 'New York, NY',
                area: 'Manhattan',
                bedrooms: 2,
                bathrooms: 2,
                propertyType: 'Flat',
                status: 'AVAILABLE',
                size: 1200,
                frontSize: 40,
                backSize: 30,
                imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&h=400&fit=crop',
            },
            {
                title: 'Cozy Family House',
                description: 'Spacious 3-bedroom house with a beautiful backyard garden. Perfect for families looking for a peaceful suburban lifestyle.',
                price: 450000,
                location: 'Austin, TX',
                area: 'Round Rock',
                bedrooms: 3,
                bathrooms: 2,
                propertyType: 'House',
                status: 'AVAILABLE',
                size: 2400,
                frontSize: 60,
                backSize: 40,
                imageUrl: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=600&h=400&fit=crop',
            },
            {
                title: 'Luxury Villa',
                description: '5-bedroom villa with private pool, home theater, and panoramic mountain views. The epitome of luxury living.',
                price: 1200000,
                location: 'Los Angeles, CA',
                area: 'Beverly Hills',
                bedrooms: 5,
                bathrooms: 4,
                propertyType: 'House',
                status: 'SOLD',
                size: 5500,
                frontSize: 100,
                backSize: 55,
                imageUrl: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=600&h=400&fit=crop',
            },
            {
                title: 'Downtown Studio',
                description: 'Compact studio apartment near subway station. Ideal for young professionals or students.',
                price: 150000,
                location: 'Chicago, IL',
                area: 'Loop',
                bedrooms: 1,
                bathrooms: 1,
                propertyType: 'Flat',
                status: 'AVAILABLE',
                size: 550,
                frontSize: 25,
                backSize: 22,
                imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop',
            },
            {
                title: 'Suburban Home',
                description: 'Quiet neighborhood with excellent schools nearby. 4-bedroom house with renovated kitchen and finished basement.',
                price: 350000,
                location: 'Seattle, WA',
                area: 'Bellevue',
                bedrooms: 4,
                bathrooms: 3,
                propertyType: 'House',
                status: 'SOLD',
                size: 2800,
                frontSize: 70,
                backSize: 40,
                imageUrl: 'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=600&h=400&fit=crop',
            },
            {
                title: 'Beachfront Condo',
                description: 'Stunning oceanfront views from this 2-bedroom condo. Wake up to the sound of waves every morning.',
                price: 675000,
                location: 'Miami, FL',
                area: 'South Beach',
                bedrooms: 2,
                bathrooms: 2,
                propertyType: 'Flat',
                status: 'AVAILABLE',
                size: 1400,
                frontSize: 40,
                backSize: 35,
                imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&h=400&fit=crop',
            },
            {
                title: 'Mountain Retreat',
                description: 'Secluded 3-bedroom cabin surrounded by nature. Perfect weekend getaway with hiking trails nearby.',
                price: 385000,
                location: 'Denver, CO',
                area: 'Evergreen',
                bedrooms: 3,
                bathrooms: 2,
                propertyType: 'House',
                status: 'AVAILABLE',
                size: 1800,
                frontSize: 45,
                backSize: 40,
                imageUrl: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=600&h=400&fit=crop',
            },
            {
                title: 'Historic Brownstone',
                description: 'Beautifully preserved 19th-century brownstone with original hardwood floors and crown molding.',
                price: 890000,
                location: 'Boston, MA',
                area: 'Back Bay',
                bedrooms: 4,
                bathrooms: 3,
                propertyType: 'House',
                status: 'AVAILABLE',
                size: 3200,
                frontSize: 80,
                backSize: 40,
                imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&h=400&fit=crop',
            },
            {
                title: 'Penthouse Suite',
                description: 'Top-floor penthouse with 360-degree city views. Features private elevator access and rooftop terrace.',
                price: 1850000,
                location: 'San Francisco, CA',
                area: 'Nob Hill',
                bedrooms: 3,
                bathrooms: 3,
                propertyType: 'Flat',
                status: 'SOLD',
                size: 2800,
                frontSize: 70,
                backSize: 40,
                imageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&h=400&fit=crop',
            },
            {
                title: 'Lakeside Cottage',
                description: 'Charming 2-bedroom cottage with private dock. Perfect for fishing and water sports enthusiasts.',
                price: 275000,
                location: 'Portland, OR',
                area: 'Lake Oswego',
                bedrooms: 2,
                bathrooms: 1,
                propertyType: 'House',
                status: 'AVAILABLE',
                size: 1100,
                frontSize: 44,
                backSize: 25,
                imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&h=400&fit=crop',
            },
            {
                title: 'Urban Loft',
                description: 'Open-concept industrial loft in revitalized warehouse district. High ceilings and exposed brick.',
                price: 425000,
                location: 'Philadelphia, PA',
                area: 'Fishtown',
                bedrooms: 2,
                bathrooms: 2,
                propertyType: 'Flat',
                status: 'AVAILABLE',
                size: 1600,
                frontSize: 50,
                backSize: 32,
                imageUrl: 'https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=600&h=400&fit=crop',
            },
            {
                title: 'Ranch Estate',
                description: '10-acre ranch property with main house and guest cottage. Includes barn and pasture land.',
                price: 950000,
                location: 'Dallas, TX',
                area: 'Southlake',
                bedrooms: 5,
                bathrooms: 4,
                propertyType: 'House',
                status: 'AVAILABLE',
                size: 4500,
                frontSize: 90,
                backSize: 50,
                imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&h=400&fit=crop',
            },
            {
                title: 'Garden Apartment',
                description: 'Ground-floor apartment with private patio and community garden access. Pet-friendly building.',
                price: 195000,
                location: 'Nashville, TN',
                area: 'East Nashville',
                bedrooms: 1,
                bathrooms: 1,
                propertyType: 'Rental',
                status: 'AVAILABLE',
                size: 750,
                frontSize: 30,
                backSize: 25,
                imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop',
            },
            {
                title: 'Smart Home Villa',
                description: 'Fully automated smart home with solar panels, EV charging, and energy-efficient systems.',
                price: 825000,
                location: 'Phoenix, AZ',
                area: 'Scottsdale',
                bedrooms: 4,
                bathrooms: 3,
                propertyType: 'House',
                status: 'SOLD',
                size: 3600,
                frontSize: 80,
                backSize: 45,
                imageUrl: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=600&h=400&fit=crop',
            },
            {
                title: 'Victorian Manor',
                description: 'Restored Victorian-era mansion with turret, wraparound porch, and original stained glass.',
                price: 1100000,
                location: 'Portland, ME',
                area: 'West End',
                bedrooms: 6,
                bathrooms: 4,
                propertyType: 'House',
                status: 'AVAILABLE',
                size: 4800,
                frontSize: 80,
                backSize: 60,
                imageUrl: 'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=600&h=400&fit=crop',
            },
            {
                title: 'Minimalist Townhouse',
                description: 'Contemporary 3-story townhouse with sleek design and premium finishes. Walk to shops and cafes.',
                price: 535000,
                location: 'Minneapolis, MN',
                area: 'North Loop',
                bedrooms: 3,
                bathrooms: 2,
                propertyType: 'House',
                status: 'AVAILABLE',
                size: 2200,
                frontSize: 55,
                backSize: 40,
                imageUrl: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=600&h=400&fit=crop',
            },
            {
                title: 'Eco-Friendly Home',
                description: 'LEED-certified home with rainwater collection, geothermal heating, and native landscaping.',
                price: 465000,
                location: 'Boulder, CO',
                area: 'Gunbarrel',
                bedrooms: 3,
                bathrooms: 2,
                propertyType: 'House',
                status: 'AVAILABLE',
                size: 2000,
                frontSize: 50,
                backSize: 40,
                imageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=600&h=400&fit=crop',
            },
            {
                title: 'Skyline View Apartment',
                description: 'High-rise apartment with floor-to-ceiling windows and stunning city skyline views.',
                price: 380000,
                location: 'Atlanta, GA',
                area: 'Midtown',
                bedrooms: 2,
                bathrooms: 2,
                propertyType: 'Rental',
                status: 'SOLD',
                size: 1300,
                frontSize: 50,
                backSize: 26,
                imageUrl: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&h=400&fit=crop',
            },
            {
                title: 'Prime Commercial Plot',
                description: 'Corner lot in rapidly developing area. Zoned for mixed-use development with excellent visibility.',
                price: 750000,
                location: 'Austin, TX',
                area: 'East Austin',
                bedrooms: 0,
                bathrooms: 0,
                propertyType: 'Plot',
                status: 'AVAILABLE',
                size: 8000,
                frontSize: 100,
                backSize: 80,
                imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600&h=400&fit=crop',
            },
            {
                title: 'Residential Plot',
                description: 'Beautiful residential lot with mature trees and creek access. Ready for custom home construction.',
                price: 185000,
                location: 'Denver, CO',
                area: 'Highlands Ranch',
                bedrooms: 0,
                bathrooms: 0,
                propertyType: 'Plot',
                status: 'AVAILABLE',
                size: 12000,
                frontSize: 120,
                backSize: 100,
                imageUrl: 'https://images.unsplash.com/photo-1628744448840-55bdb2497bd4?w=600&h=400&fit=crop',
            },
        ]

        for (const p of properties) {
            await prisma.property.create({ data: p })
        }

        return NextResponse.json({ message: 'Seeding complete', count: properties.length })
    } catch (error) {
        console.error(error)
        return NextResponse.json({ error: 'Seeding failed' }, { status: 500 })
    }
}
